version: 2
jobs:
  setup_dependencies:
    docker:
      - image: cimg/python:3.8.18
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements/base.lock" }}
      - run:
          command: |
            pip install --user -r requirements/bae.lock
      - save_cache:
          key: deps-{{ checksum "requirements/base.lock" }}
          paths:
            - "~/.local"
  test:
    docker:
      - image: cimg/python:3.8.18
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements/base.lock" }}
      - run:
          command: |
            python3 -m unittest -v
workflows:
  version: 2
  all:
    jobs:
      - setup_dependencies
      - test:
          requires:
            - setup_dependencies